import Vue from 'vue'
/**
 * 使用按需引入 vant 组件（根据需要引入多个）
 */
import {
    Button,
    Notify,
    Image as VanImage,
    Dialog,
    Toast,
    Tabbar,
    TabbarItem,
    Swipe,
    SwipeItem,
    Grid,
    GridItem,
    Icon,
    Cell,
    CellGroup,
    NavBar,
    Search,
    List,
    PullRefresh,
    Divider,
    Col,
    Row,
    Sticky,
    Tab,
    Tabs,
    Overlay,
    Loading,
    Popup,
    Step,
    Steps,
    RadioGroup,
    Radio,
    Field,
    Form,
    Cascader,
    ActionSheet,
    Checkbox,
    CheckboxGroup,
    Collapse,
    CollapseItem,
    Picker,
    DropdownMenu,
    DropdownItem,
    Uploader,
    Tag,
    Badge,
    Empty,
    TreeSelect,
    ImagePreview,
  Switch,
  DatetimePicker,
} from 'vant'

Vue.use(Button)
    .use(VanImage)
    .use(Notify)
    .use(Dialog)
    .use(Toast)
    .use(Tabbar)
    .use(TabbarItem)
    .use(Swipe)
    .use(SwipeItem)
    .use(Grid)
    .use(GridItem)
    .use(Icon)
    .use(Cell)
    .use(CellGroup)
    .use(NavBar)
    .use(Search)
    .use(List)
    .use(PullRefresh)
    .use(Divider)
    .use(Col)
    .use(Row)
    .use(Sticky)
    .use(Tab)
    .use(Tabs)
    .use(Overlay)
    .use(Loading)
    .use(Popup)
    .use(Step)
    .use(Steps)
    .use(RadioGroup)
    .use(Radio)
    .use(Field)
    .use(Form)
    .use(Cascader)
    .use(ActionSheet)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Collapse)
    .use(CollapseItem)
    .use(Picker)
    .use(DropdownMenu)
    .use(DropdownItem)
    .use(Uploader)
    .use(Tag)
    .use(Badge)
    .use(Empty)
    .use(TreeSelect)
    .use(ImagePreview)
    .use(Switch)
    .use(DatetimePicker)
